"""profile domain: extended profile fields, skills/interests taxonomy, identity photo

Revision ID: 054f6af45a96
Revises: 87d38e0c0a49
Create Date: 2026-09-19 12:05:32.893409

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '054f6af45a96'
down_revision: str | Sequence[str] | None = '87d38e0c0a49'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), server_default='INTEREST', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interests_name'), 'interests', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('profile_interests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('interest_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), server_default='manual', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'interest_id')
    )
    op.create_index('ix_profile_interests_interest_id', 'profile_interests', ['interest_id'], unique=False)
    op.create_table('profile_skills',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), server_default='manual', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_id')
    )
    op.create_index('ix_profile_skills_skill_id', 'profile_skills', ['skill_id'], unique=False)
    op.add_column('profiles', sa.Column('headline', sa.String(length=150), nullable=True))
    op.add_column('profiles', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('github_url', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('portfolio_url', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('career_interests', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('research_interests', sa.Text(), nullable=True))
    op.add_column('university_identities', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university_identities', 'photo_url')
    op.drop_column('profiles', 'research_interests')
    op.drop_column('profiles', 'career_interests')
    op.drop_column('profiles', 'website_url')
    op.drop_column('profiles', 'portfolio_url')
    op.drop_column('profiles', 'linkedin_url')
    op.drop_column('profiles', 'github_url')
    op.drop_column('profiles', 'avatar_url')
    op.drop_column('profiles', 'headline')
    op.drop_index('ix_profile_skills_skill_id', table_name='profile_skills')
    op.drop_table('profile_skills')
    op.drop_index('ix_profile_interests_interest_id', table_name='profile_interests')
    op.drop_table('profile_interests')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_interests_name'), table_name='interests')
    op.drop_table('interests')
    # ### end Alembic commands ###
